<?php require 'inc.php'; need('admin');
if($_POST){$a=$_POST['a'];
 if($a=='addsv')q("INSERT INTO services(department,name,code,avg_min) VALUES(?,?,?,?)",[$_POST['department'],$_POST['name'],strtoupper(substr($_POST['code'],0,4)),max(1,(int)$_POST['avg_min'])]);
 if($a=='delsv')q("DELETE FROM services WHERE id=?",[(int)$_POST['id']]);
 if($a=='addstaff')q("INSERT INTO users(name,email,password,role,service_id) VALUES(?,?,?,'staff',?)",[$_POST['name'],$_POST['email'],password_hash($_POST['password'],PASSWORD_DEFAULT),(int)$_POST['service_id']]);
 if($a=='deluser')q("DELETE FROM users WHERE id=? AND role<>'admin'",[(int)$_POST['id']]);
 header('Location: admin.php');exit;}
$st=q("SELECT COUNT(*) total,SUM(status='done') done,SUM(status='waiting') waiting,SUM(status='cancelled') cancelled,AVG(TIMESTAMPDIFF(MINUTE,created_at,served_at)) wait FROM queue WHERE qdate=CURDATE()")->fetch();
$svs=q("SELECT * FROM services")->fetchAll();$us=q("SELECT u.*,s.name sn FROM users u LEFT JOIN services s ON s.id=u.service_id ORDER BY role,id")->fetchAll();
$rep=q("SELECT s.department,s.name,COUNT(q.id) t,SUM(q.status='done') d FROM services s LEFT JOIN queue q ON q.service_id=s.id AND q.qdate=CURDATE() GROUP BY s.id")->fetchAll();
top(); ?>
<h4>Today's Statistics</h4><div class="row text-center mb-4"><?php foreach([['Total Tokens',$st['total']],['Completed',$st['done']],['Waiting',$st['waiting']],['Cancelled',$st['cancelled']],['Avg Wait (min)',round($st['wait']??0)]] as $c):?><div class="col"><div class="card card-body"><small><?=$c[0]?></small><h3><?=(int)$c[1]?></h3></div></div><?php endforeach;?></div>
<h5>Report by Service</h5><table class="table table-sm bg-white"><tr><th>Department</th><th>Service</th><th>Tokens</th><th>Completed</th></tr><?php foreach($rep as $r):?><tr><td><?=h($r['department'])?></td><td><?=h($r['name'])?></td><td><?=$r['t']?></td><td><?=(int)$r['d']?></td></tr><?php endforeach;?></table>
<h5 class="mt-4">Services</h5><table class="table table-sm bg-white"><tr><th>Code</th><th>Department</th><th>Service</th><th>Avg min</th><th></th></tr><?php foreach($svs as $s):?><tr><td><?=h($s['code'])?></td><td><?=h($s['department'])?></td><td><?=h($s['name'])?></td><td><?=$s['avg_min']?></td><td><form method="post" onsubmit="return confirm('Delete?')"><input type="hidden" name="id" value="<?=$s['id']?>"><button name="a" value="delsv" class="btn btn-sm btn-danger">Delete</button></form></td></tr><?php endforeach;?></table>
<form method="post" class="row g-2 mb-4"><input type="hidden" name="a" value="addsv"><div class="col"><input class="form-control" name="department" placeholder="Department" required></div><div class="col"><input class="form-control" name="name" placeholder="Service" required></div><div class="col-2"><input class="form-control" name="code" placeholder="Code" required></div><div class="col-2"><input class="form-control" type="number" name="avg_min" value="5"></div><div class="col"><button class="btn btn-primary">Add Service</button></div></form>
<h5>Users</h5><table class="table table-sm bg-white"><tr><th>Name</th><th>Email</th><th>Role</th><th>Service</th><th></th></tr><?php foreach($us as $u):?><tr><td><?=h($u['name'])?></td><td><?=h($u['email'])?></td><td><?=$u['role']?></td><td><?=h($u['sn'])?></td><td><?php if($u['role']!='admin'):?><form method="post" onsubmit="return confirm('Delete?')"><input type="hidden" name="id" value="<?=$u['id']?>"><button name="a" value="deluser" class="btn btn-sm btn-danger">Delete</button></form><?php endif;?></td></tr><?php endforeach;?></table>
<form method="post" class="row g-2"><input type="hidden" name="a" value="addstaff"><div class="col"><input class="form-control" name="name" placeholder="Staff name" required></div><div class="col"><input class="form-control" type="email" name="email" placeholder="Email" required></div><div class="col"><input class="form-control" name="password" placeholder="Password" required></div><div class="col"><select class="form-select" name="service_id"><?php foreach($svs as $s)echo "<option value='{$s['id']}'>".h($s['name'])."</option>";?></select></div><div class="col"><button class="btn btn-primary">Add Staff</button></div></form>
<?php bottom();
